using System.ComponentModel.DataAnnotations;

namespace MigrationTool.SK.Models;

internal class Individual
{
	public string? LOC_ID { get; set; }
	public required int REC_ID { get; set; }
	[Key] public required string IND_ID { get; set; }
	public required string FAMILY_ID { get; set; }
	public string? TITLE { get; set; }
	public string? SUFFIX { get; set; }
	public string? FIRST_NAME { get; set; }
	public string? MID_NAME { get; set; }
	public string? LAST_NAME { get; set; }
	public string? PREFERNAME { get; set; }
	public string? ACTIVE_IND { get; set; }
	public string? ENV_NO { get; set; }
	public string? SALUTATION { get; set; }
	public string? SEX { get; set; }
	public string? BIRTH_DT { get; set; }
	public string? AGE { get; set; }
	public string? AGE_GROUP { get; set; }
	public string? MARITAL_CD { get; set; }
	public string? WEDDING_DT { get; set; }
	public string? ADDR1 { get; set; }
	public string? ADDR2 { get; set; }
	public string? CITY { get; set; }
	public string? STATE { get; set; }
	public string? ZIP { get; set; }
	public string? CARSORT { get; set; }
	public string? COUNTRY { get; set; }
	public string? GEO_CD { get; set; }
	public string? A_EFF_DT { get; set; }
	public string? A_END_DT { get; set; }
	public string? NO_ALT_IND { get; set; }
	public string? A_ADDR1 { get; set; }
	public string? A_ADDR2 { get; set; }
	public string? A_DEVPOINT { get; set; }
	public string? A_CITY { get; set; }
	public string? A_STATE { get; set; }
	public string? A_ZIP { get; set; }
	public string? A_CARSORT { get; set; }
	public string? A_COUNTRY { get; set; }
	public string? A_PHONE { get; set; }
	public string? A_UNLIST { get; set; }
	public string? H_PHONE { get; set; }
	public string? H_UNLIST { get; set; }
	public string? W_PHONE { get; set; }
	public string? W_UNLIST { get; set; }
	public string? W_EXT { get; set; }
	public string? C_PHONE { get; set; }
	public string? C_UNLIST { get; set; }
	public string? C_EXT { get; set; }
	public string? PAGER { get; set; }
	public string? P_UNLIST { get; set; }
	public string? PAGER_EXT { get; set; }
	public string? FAX { get; set; }
	public string? F_UNLIST { get; set; }
	public string? FAX_EXT { get; set; }
	public string? EMAIL1 { get; set; }
	public string? EMAIL1_IND { get; set; }
	public string? EMAIL2 { get; set; }
	public string? EMAIL2_IND { get; set; }
	public string? EMAIL3 { get; set; }
	public string? EMAIL3_IND { get; set; }
	public string? URL { get; set; }
	public string? URL_IND { get; set; }
	public string? STATUS { get; set; }
	public string? JOB_CD { get; set; }
	public string? EMPLOYER { get; set; }
	public string? HOMECHURCH { get; set; }
	public string? PASTOR_CD { get; set; }
	public string? LAYMAN_CD { get; set; }
	public string? CH_BKGD_CD { get; set; }
	public string? MEM_STATUS { get; set; }
	public string? MEM_DT { get; set; }
	public string? JOIN_DT { get; set; }
	public string? HOW_JOIN { get; set; }
	public string? SUNSCHOOL { get; set; }
	public string? GROUP_CD { get; set; }
	public string? FELLOW_GRP { get; set; }
	public string? BAPTIZED { get; set; }
	public string? BAPTIZE_DT { get; set; }
	public string? CONF_IND { get; set; }
	public string? CONF_DT { get; set; }
	public string? GRADE { get; set; }
	public string? GRADE_DT { get; set; }
	public string? RELAT_CD { get; set; }
	public string? HEAD_ID { get; set; }
	public string? SPOUSE_ID { get; set; }
	public string? INCLD_DIR { get; set; }
	public string? DEV_POINT { get; set; }
	public string? NOTE { get; set; }
	public string? TEACHER_CD { get; set; }
	public string? CLASS_CD { get; set; }
	public string? UDF1 { get; set; }
	public string? UDF2 { get; set; }
	public string? UDF3 { get; set; }
	public string? UDF4 { get; set; }
	public string? UDF5 { get; set; }
	public string? UDF6 { get; set; }
	public string? UDF7 { get; set; }
	public string? UDF8 { get; set; }
	public string? UDF9 { get; set; }
	public string? UDF10 { get; set; }
	public string? UDF11 { get; set; }
	public string? UDF12 { get; set; }
	public string? UDF13 { get; set; }
	public string? UDF14 { get; set; }
	public string? UDF15 { get; set; }
	public string? UDF16 { get; set; }
	public string? UDF_DT1 { get; set; }
	public string? UDF_DT2 { get; set; }
	public string? UDF_DT3 { get; set; }
	public string? UDF_DT4 { get; set; }
	public string? UDF_DT5 { get; set; }
	public string? UDF_DT6 { get; set; }
	public string? UDF_DT7 { get; set; }
	public string? UDF_DT8 { get; set; }
	public string? UDF_DT9 { get; set; }
	public string? UDF_DT10 { get; set; }
	public string? UDF_PHONE1 { get; set; }
	public string? UDF_EXT1 { get; set; }
	public string? UDF_UNLST1 { get; set; }
	public string? UDF_PHONE2 { get; set; }
	public string? UDF_EXT2 { get; set; }
	public string? UDF_UNLST2 { get; set; }
	public string? UDF_PHONE3 { get; set; }
	public string? UDF_EXT3 { get; set; }
	public string? UDF_UNLST3 { get; set; }
	public string? UDF_PHONE4 { get; set; }
	public string? UDF_EXT4 { get; set; }
	public string? UDF_UNLST4 { get; set; }
	public string? UDF_PHONE5 { get; set; }
	public string? UDF_EXT5 { get; set; }
	public string? UDF_UNLST5 { get; set; }
	public string? UDF_CHECK1 { get; set; }
	public string? UDF_CHECK2 { get; set; }
	public string? UDF_CHECK3 { get; set; }
	public string? UDF_CHECK4 { get; set; }
	public string? UDF_CHECK5 { get; set; }
	public string? UDF_CHECK6 { get; set; }
	public string? UDF_CHECK7 { get; set; }
	public string? UDF_CHECK8 { get; set; }
	public string? UDF_CHECK9 { get; set; }
	public string? UDF_CHK10 { get; set; }
	public string? MAID_NAME { get; set; }
	public string? MAIL_ADDR { get; set; }
	public string? unl_addr { get; set; }
	public string? unl_al_addr { get; set; }
	public string? attrib_pri { get; set; }
	public string? attrib1_pri { get; set; }
	public string? attrib2_pri { get; set; }
	public string? attrib3_pri { get; set; }
	public string? attrib4_pri { get; set; }
	public string? attrib5_pri { get; set; }
	public string? attrib6_pri { get; set; }
	public string? attrib7_pri { get; set; }
	public string? attrib8_pri { get; set; }
	public string? CONTACT { get; set; }
	public string? youth1 { get; set; }
	public string? youth2 { get; set; }
	public string? youth3 { get; set; }
	public string? youth4 { get; set; }
	public string? youth5 { get; set; }
	public string? youth6 { get; set; }
	public string? youth7 { get; set; }
	public string? youth8 { get; set; }
	public string? youth9 { get; set; }
	public string? youth10 { get; set; }
	public string? youth11 { get; set; }
	public string? youth12 { get; set; }
	public string? youth13 { get; set; }
	public string? youth14 { get; set; }
	public string? youth15 { get; set; }
	public string? youth16 { get; set; }
	public string? youth17 { get; set; }
	public string? youth18 { get; set; }
	public string? youth19 { get; set; }
	public string? youth20 { get; set; }
	public string? youth21 { get; set; }
	public string? OLD_IND_ID { get; set; }
	public string? CREATE_TS { get; set; }
	public string? CREATE_BY { get; set; }
	public string? UPDATE_TS { get; set; }
	public string? UPDATE_BY { get; set; }
	public string? cross_dir { get; set; }
	public string? PHOTO_IND { get; set; }
	public string? EST_IND { get; set; }
	public string? NUM1 { get; set; }
	public string? NUM2 { get; set; }
	public string? NUM3 { get; set; }
	public string? NUM4 { get; set; }
	public DateTime? pmm_date { get; set; }
}
